# Generated by Django 4.2 on 2023-04-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0002_projet_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('En_avance', models.BooleanField(default=False)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArtyProd.projet')),
            ],
        ),
    ]
