# Generated by Django 4.2 on 2023-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0003_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('terminee', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='acheve',
            new_name='En_avance',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='En_avance',
        ),
        migrations.AddField(
            model_name='projet',
            name='taches',
            field=models.ManyToManyField(to='ArtyProd.tache'),
        ),
    ]
