# Generated by Django 4.2 on 2023-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0004_tache_rename_acheve_projet_en_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='terminee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tache',
            name='En_avance',
            field=models.BooleanField(default=False),
        ),
    ]
