# Generated by Django 4.2 on 2023-04-29 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0006_service_remove_projet_taches_delete_personnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('fichier', models.FileField(blank=True, upload_to='media/')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArtyProd.equipe')),
                ('services', models.ManyToManyField(through='ArtyProd.Detail', to='ArtyProd.service')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet'),
        ),
        migrations.AddField(
            model_name='detail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service'),
        ),
    ]
