# Generated by Django 4.2 on 2023-04-29 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArtyProd', '0007_detail_equipe_projet_detail_projet_detail_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='ArtyProd.equipe')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
