# Generated by Django 4.2 on 2023-05-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0009_tache_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='utilisateur',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='personnel',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
