# Generated by Django 4.2 on 2023-05-16 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0011_projet_customer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='personnel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.personnel'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='assignee_a',
            field=models.ManyToManyField(blank=True, related_name='assigned_to_taches', to='ArtyProd.personnel'),
        ),
    ]
