# Generated by Django 4.2 on 2023-05-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0014_alter_tache_personnel_alter_tache_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='personnel',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Tache', to='ArtyProd.personnel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Tache', to='ArtyProd.projet'),
            preserve_default=False,
        ),
    ]
